prep-html-script-tag-Carolyne Golias
GCarolyne/javascript-prep-0924-code-solutions pull request #3
Opened 2024-09-30 00:53 UTC by GCarolyne

2024-09-30 00:53 UTC, GCarolyne commented
<img width="728" alt="Screenshot 2024-09-29 at 5 26 46 PM" src="https://github.com/user-attachments/assets/5d3f9052-3d26-45e4-8805-f3dc21ae9d13">

2024-09-30 15:59 UTC, shawnkost requested changes
One change here Carolyne!

2024-09-30 15:59 UTC, shawnkost commented on prep-html-script-tag/index.html
> +      </script>
For this one, you should not have anything in-between the opening and closing `script` tag. You'll just load in the `main.js` file and your `console.log` will just be in there

2024-10-01 23:02 UTC, robgmerrill approved these changes
👍

2024-10-02 01:07 UTC, merged